# Generated by Django 4.2.28 on 2026-02-21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plots", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION plots_prevent_overlap()
                RETURNS trigger AS $$
                BEGIN
                    IF NEW.geometry IS NULL THEN
                        RETURN NEW;
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM plots_plot p
                        WHERE p.id <> COALESCE(NEW.id, -1)
                          AND ST_Intersects(p.geometry, NEW.geometry)
                    ) THEN
                        RAISE EXCEPTION 'This plot overlaps an existing plot.'
                            USING ERRCODE = '23514';
                    END IF;

                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                DROP TRIGGER IF EXISTS trg_plots_prevent_overlap ON plots_plot;
                CREATE TRIGGER trg_plots_prevent_overlap
                BEFORE INSERT OR UPDATE OF geometry ON plots_plot
                FOR EACH ROW
                EXECUTE FUNCTION plots_prevent_overlap();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_plots_prevent_overlap ON plots_plot;
                DROP FUNCTION IF EXISTS plots_prevent_overlap();
            """,
        ),
    ]
