# Generated by Django 4.2.28 on 2026-02-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('geometry',), name='unique_plot_geometry'),
        ),
    ]
